import { DatasetModel, ModelTraining, ProblemModel } from './models';

export const dummyProblems: ProblemModel[] = [
  {
    id: 0,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 1',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: true,
    submissions_count: 12,
    solved: false,
  },
  {
    id: 1,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 2',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: false,
    submissions_count: 12,
    solved: false,
  },
  {
    id: 2,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 3',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: false,
    submissions_count: 12,
    solved: false,
  },
  {
    id: 3,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 4',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: true,
    submissions_count: 12,
    solved: true,
  },

  {
    id: 4,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 5',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: true,
    submissions_count: 12,
    solved: true,
  },
  {
    id: 5,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 6',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: true,
    submissions_count: 12,
    solved: true,
  },
  {
    id: 6,
    user_address: 'ADDR1',
    timestamp: 1710545142091,
    deadline: 1710548142091,
    title: 'Test problem 7',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    reward: 69,
    has_dataset: true,
    submissions_count: 12,
    solved: true,
  },
];

export const dummyDatasets: DatasetModel[] = [
  {
    id: 0,
    problem: {
      id: 4,
      user_address: 'ADDR1',
      timestamp: 1710545142091,
      deadline: 1710548142091,
      title: 'Test problem 5',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      reward: 69,
      has_dataset: true,
      submissions_count: 12,
      solved: true,
    },
    description:
      'Dataset description about dataset data and info about models and files and all that',
    file_url: 'testurl',
    timestamp: 171054514000,
    author: '0x0123-9-12039-120393',
  },
  {
    id: 1,
    problem: {
      id: 6,
      user_address: 'ADDR1',
      timestamp: 1710545142091,
      deadline: 1710548142091,
      title: 'Test problem 7',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      reward: 69,
      has_dataset: true,
      submissions_count: 12,
      solved: true,
    },
    description:
      'Dataset description about dataset data and info about models and files and all that',
    file_url: 'testurl',
    timestamp: 171054514000,
    author: '0x0123-9-12039-120393',
  },
  {
    id: 2,
    problem: {
      id: 4,
      user_address: 'ADDR1',
      timestamp: 1710545142091,
      deadline: 1710548142091,
      title: 'Test problem 5',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      reward: 69,
      has_dataset: true,
      submissions_count: 12,
      solved: true,
    },
    description:
      'Dataset description about dataset data and info about models and files and all that',
    file_url: 'testurl',
    timestamp: 171054514000,
    author: '0x0123-9-12039-120393',
  },
  {
    id: 3,
    problem: {
      id: 4,
      user_address: 'ADDR1',
      timestamp: 1710545142091,
      deadline: 1710548142091,
      title: 'Test problem 5',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      reward: 69,
      has_dataset: true,
      submissions_count: 12,
      solved: true,
    },
    description:
      'Dataset description about dataset data and info about models and files and all that',
    file_url: 'testurl',
    timestamp: 171054514000,
    author: '0x0123-9-12039-120393',
  },
  {
    id: 4,
    problem: {
      id: 6,
      user_address: 'ADDR1',
      timestamp: 1710545142091,
      deadline: 1710548142091,
      title: 'Test problem 7',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      reward: 69,
      has_dataset: true,
      submissions_count: 12,
      solved: true,
    },
    description:
      'Dataset description about dataset data and info about models and files and all that',
    file_url: 'testurl',
    timestamp: 171054514000,
    author: '0x0123-9-12039-120393',
  },
  {
    id: 5,
    problem: {
      id: 4,
      user_address: 'ADDR1',
      timestamp: 1710545142091,
      deadline: 1710548142091,
      title: 'Test problem 5',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      reward: 69,
      has_dataset: true,
      submissions_count: 12,
      solved: true,
    },
    description:
      'Dataset description about dataset data and info about models and files and all that',
    file_url: 'testurl',
    timestamp: 171054514000,
    author: '0x0123-9-12039-120393',
  },
];

export const dummyModels: ModelTraining[] = [
  {
    id: 0,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 1,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 1,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 2,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 2,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 0,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 3,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 1,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 4,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 4,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 5,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 5,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 6,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 0,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 7,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 1,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 8,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 2,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
  {
    id: 9,
    author: '0x3413-1203-1023',
    timestamp: 171054514000,
    problem_id: 3,
    model: 'url do modela',
    size: '230MB',
    data_id: undefined,
    description: 'Description of the model that someone submitted',
  },
];
